import './globals.css'; // <-- DÒNG NÀY LÀ MẠNG SỐNG CỦA UI
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Hệ Thống Học Tiếng Nhật AI',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body>{children}</body>
    </html>
  );
}